### ISSUE TITLE
Calling PollJob before JobWorker causes panic

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/libzbc#1]
Calling PollJob before JobWorker causes a panic which crashes the whole program. I get that it doesn't make sense to do this, but hopefully it shouldn't crash the whole thing :sweat_smile: 

Here's the trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7f630e42c3d2]

goroutine 21 [running]:
main.(*EventMap).GetEvent(...)
	/go/src/github.com/zeebe-io/libzbc/event_map.go:26
main.PollJob.func1(0xc400000001, 0xc4201922a0, 0xc420166180)
	/go/src/github.com/zeebe-io/libzbc/main.go:115 +0x62
created by main.PollJob
	/go/src/github.com/zeebe-io/libzbc/main.go:112 +0x12c
[1]    23695 abort (core dumped)  bin/console
```

**Comment by jsam** [comment]
This is completely intentional, cause misuse should be very much visible. ;)

We decided for now to support only 1 job worker (cause we officially only support node and it makes sense there). As this is gonna probably change in the near future as we gonna support more languages which do not have this constraint, this will change.

Thanks for reporting.
